### PR TITLE
fix #13 setValue, register and unregister should be optional 

### LINKED ISSUE #13: setValue and register props are not optional when inside FormContext
Hey there,

I am implementing RHFInput in a typescript project.

I'm not sure if i am making a mistake in my code somewhere but I am trying to use RHFInput like this:

image

but I get an error telling me that they are both required.

Am i using this wrong? if not can i submit a PR?

P.S. Love your library, great work  👍.

### PR DESCRIPTION
**Pull request by RiccardoCampitelli**
useFormHook setValue, register and unregister props are now optional.

I check if they are provided via props or context and if not throw an error.

Please let me know if there is anything i can do better, this is my first OS contribution :)

### CODE REVIEW

**Comment by bluebill1049** [comment]
aha, thank you! I live by your words. love it.

**Comment by bluebill1049** [comment]
your first ever contribution too. So good! thank you for your contribution.

File: src/index.tsx [hunk 1]
```diff
@@ -40,9 +40,30 @@ const RHFInput = React.memo(
     const [inputValue, setInputValue] = React.useState(defaultData);
     const valueRef = React.useRef(defaultData);
     const methods = useFormContext();
-    const setValue = methods ? methods.setValue : setValueFromProp;
-    const register = methods ? methods.register : registerFromProp;
-    const unregister = methods ? methods.unregister : unregisterFromProp;
+    const setValue =
+      setValueFromProp !== undefined
```
Comment (bluebill1049) [inline src/index.tsx:44]: I think we can make it simpler to  `setValueFromProp ?  methods.setValue :  setValueFromProp`. But you know what lovely work I will approve it anyhow.

**Review by bluebill1049 — APPROVED** [review]
